BlueTravelWeb/src/cz/ucl/jsf/controller/CustomerController.java
package cz.ucl.jsf.controller;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import cz.ucl.bt.ejb.CustomerManager;
import cz.ucl.bt.model.ConfirmationStatus;
import cz.ucl.bt.model.Customer;

@ManagedBean(name = "customerController")
@ViewScoped
public class CustomerController implements Serializable {
    private static final long serialVersionUID = -4646329764605891472L;

    private String searchSurname;
    private List<Customer> customersFound;
    private Long selectedCustomerId;
    private Customer currentCustomer;

    @EJB
    private CustomerManager manager;

    public String getSearchSurname() {
        return searchSurname;
    }

    public void setSearchSurname(String searchSurname) {
        this.searchSurname = searchSurname;
    }

    public Long getSelectedCustomerId() {
        return selectedCustomerId;
    }

    public void setSelectedCustomerId(Long selectedClientId) {
        this.selectedCustomerId = selectedClientId;
    }

    public List<Customer> getCustomersFound() {
        return customersFound;
    }

    public Customer getCurrentCustomer() {
        if (currentCustomer == null) {
            currentCustomer = manager.loadCustomer(selectedCustomerId);
        }

        return currentCustomer;
    }

    public void searchCustomers() {
        customersFound = manager.findCustomersBySurnamePrefix(searchSurname);
    }

    public Map<ConfirmationStatus, String> getBackgroundColor() {
        Map<ConfirmationStatus, String> colors = new HashMap<ConfirmationStatus, String>();
        colors.put(ConfirmationStatus.Undecided, "yellow");
        colors.put(ConfirmationStatus.Confirmed, "#7FFFD4");
        colors.put(ConfirmationStatus.Refused, "#FA8072");
        return colors;
    }

    @PostConstruct
    public void init() {
        System.out.println("!!! Customer Controller initialized for VIEW SCOPE: " + this.toString());
    }

    @PreDestroy
    public void destroy() {
        System.out.println("!!! Customer Controller destroyed at the end of the VIEW SCOPE: " + this.toString());
    }
}

BlueTravelWeb/src/cz/ucl/jsf/controller/PurchaseController.java
package cz.ucl.jsf.controller;

import java.io.Serializable;
import java.util.Map;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import cz.ucl.bt.ejb.PurchaseManager;
import cz.ucl.bt.model.Contract;
import cz.ucl.bt.model.CreditCard;
import cz.ucl.bt.model.Customer;
import cz.ucl.bt.model.Traveller;

@ManagedBean(name = "purchaseController")
@SessionScoped
public class PurchaseController implements Serializable {
    private static final long serialVersionUID = -8118331554543394402L;
    @EJB
    private PurchaseManager manager;

    private Contract contract;
    private Traveller currentTraveller;
    private long selectedTravellerId;

    private Map<String, Long> allTrips;

    private String[] creditCardNo = new String[4];
    private String[] creditCardValidity = new String[2];

    public Contract getContract() {
        if (contract == null) {
            contract = new Contract();

            Customer customer = new Customer();
            contract.setCustomer(customer);
        }
        return contract;
    }

    public Traveller getCurrentTraveller() {
        if (currentTraveller == null) {
            currentTraveller = new Traveller();
        }
        return currentTraveller;
    }

    public void setSelectedTravellerId(Long selectedTravellerId) {
        this.selectedTravellerId = selectedTravellerId;
    }

    public void setContract(Contract contract) {
        this.contract = contract;
    }

    public Map<String, Long> getAllTrips() {
        if (allTrips == null) {
            allTrips = manager.getTripNameIdMap();
            allTrips.put("", -1L);
        }
        return allTrips;
    }

    public String[] getCreditCardNo() {
        return creditCardNo;
    }

    public void setCreditCardNo(String[] creditCardNo) {
        this.creditCardNo = creditCardNo;
    }

    public String[] getCreditCardValidity() {
        return creditCardValidity;
    }

    public void setCreditCardValidity(String[] creditCardValidity) {
        this.creditCardValidity = creditCardValidity;
    }

    public long getSelectedTripId() {
        if (getContract().getHoliday() != null)
            return getContract().getHoliday().getId();
        else
            return -1;
    }

    public void setSelectedTripId(long selectedTripId) {
        if (selectedTripId != -1) {
            contract.setHoliday(manager.loadHoliday(selectedTripId));
        }
    }

    public void selectTraveller() {
        for (Traveller traveller : contract.getTravellers()) {
            if (traveller.getId() != null
                    && traveller.getId() == selectedTravellerId) {
                currentTraveller = traveller;
                break;
            } else if (traveller.getId() == null
                    && traveller.hashCode() == selectedTravellerId) {
                currentTraveller = traveller;
                break;
            }

        }
    }

    public void saveTraveller() {
        contract.addTraveller(currentTraveller);
        currentTraveller = new Traveller();
    }

    public void newTraveller() {
        currentTraveller = new Traveller();
    }

    public int travellerHashCode(Traveller t) {
        return t.hashCode();
    }

    public void removeTraveller() {
        Traveller selectedTraveller = null;
        for (Traveller traveller : contract.getTravellers()) {
            if (traveller.getId() != null
                    && traveller.getId() == selectedTravellerId) {
                selectedTraveller = traveller;
                break;
            } else if (traveller.getId() == null
                    && traveller.hashCode() == selectedTravellerId) {
                selectedTraveller = traveller;
                break;
            }
        }

        contract.getTravellers().remove(selectedTraveller);

        if (currentTraveller == selectedTraveller)
            currentTraveller = new Traveller();
    }

    public void copyTravellerFromCustomer() {
        currentTraveller = new Traveller();
        currentTraveller.setSurname(contract.getCustomer().getSurname());
        currentTraveller.setFirstName(contract.getCustomer().getFirstName());

    }

    public Double getCalculatedPrice() {
        if (contract.getHoliday() != null) {
            Double basePrice = contract.getHoliday().getPrice();
            return basePrice * contract.getTravellers().size();
        } else {
            return null;
        }
    }

    public String confirmContract() {

        CreditCard card = new CreditCard();
        card.setNumber(creditCardNo[0] + creditCardNo[1] + creditCardNo[2]
                + creditCardNo[3]);

        if (card.getNumber().length() != 16) {
            FacesContext.getCurrentInstance().addMessage(
                    null,
                    new FacesMessage("Wrong credit card number",
                            "The credit card number is wrong"));
            return "validationError";
        } else {
            card.setValidity(creditCardValidity[0] + creditCardValidity[1]);
            card.setOwnerName(contract.getCustomer().getName());
            contract.getCustomer().setCard(card);

            manager.saveContractNewCustomer(contract, contract.getHoliday()
                    .getId());
        }

        this.contract = null;
        this.creditCardNo = new String[4];
        this.creditCardValidity = new String[2];
        this.currentTraveller = null;

        return "confirmed";
    }

}

BlueTravelWeb/src/cz/ucl/jsf/controller/TripConfigurationController.java
package cz.ucl.jsf.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import cz.ucl.bt.ejb.TripConfigurationManager;
import cz.ucl.bt.model.Accommodation;
import cz.ucl.bt.model.Holiday;
import cz.ucl.bt.model.Transportation;

@ManagedBean(name = "holidayManager")
@SessionScoped
public class TripConfigurationController implements Serializable {
    private static final long serialVersionUID = 8691026176654134193L;

    private Holiday currentHoliday;
    private Accommodation currentAccommodation;
    private Transportation transportExample;

    private Long currentHolidayId;
    private Long transportId;
    private Long accommodationId;

    @EJB
    private TripConfigurationManager manager;


    public List<Holiday> getAllHolidays() {
        return manager.getFixedTrips();
    }

    public Holiday getCurrentHoliday() {
        if (currentHoliday == null) {
            if (currentHolidayId != null) {
                currentHoliday = manager.loadCompleteTrip(currentHolidayId);
            } else {
                currentHoliday = new Holiday();
            }
        }

        return currentHoliday;
    }


    public Accommodation getCurrentAccommodation() {
        if (currentAccommodation == null) {
            currentAccommodation = new Accommodation();
        }
        return currentAccommodation;
    }

    public void setCurrentHolidayId(Long id) {
        if (id != null && !id.equals(currentHolidayId)) {
            currentHolidayId = id;

            transportId = null;
            accommodationId = null;

            currentHoliday = null;
            currentAccommodation = null;
            transportExample = null;

            currentHoliday = getCurrentHoliday();
            currentAccommodation = getCurrentAccommodation();
            transportExample = getTransportExample();
        }

    }

    public Long getCurrentHolidayId() {
        return currentHolidayId;
    }

    public Transportation getTransportExample() {
        if (transportExample == null)
            transportExample = new Transportation();
        return transportExample;
    }

    public void setAccommodationId(Long accommodationId) {
        this.accommodationId = accommodationId;
    }

    public void setTransportId(Long transportId) {
        this.transportId = transportId;
    }

    public List<String> getAllFromCities() {
        return manager.getAllFromCities();
    }

    public List<String> getAllToCities() {
        return manager.getAllToCities();
    }

    public List<String> getAllHotelCities() {
        return manager.getAllHotelCities();
    }

    public List<String> getHotelsForSelectedCity() {
        if (getCurrentAccommodation().getLocation() != null && !"".equals(getCurrentAccommodation().getLocation()))
            return manager.getHotelsForCity(getCurrentAccommodation().getLocation());
        else return new ArrayList<>();
    }

    public void removeTransport() {
        manager.removeTransportFromTrip(currentHoliday.getId(), transportId);

        for (Transportation t : getCurrentHoliday().getTransportation()) {
            if (t.getId().equals(transportId)) {
                getCurrentHoliday().getTransportation().remove(t);
                break;
            }
        }

    }

    public String saveHoliday() {
        currentHoliday = manager.saveHoliday(currentHoliday);

        return "holiday_saved";
    }

    public void addTransport() {
        currentHoliday.getTransportation().add(manager.loadTransportation(this.transportId));
        currentHoliday = manager.saveHoliday(currentHoliday);
    }

    public void addAccommodation() {
        if (currentAccommodation.getLocation() != null) {
            manager.addAccommodation(getCurrentHolidayId(),currentAccommodation);
            currentHoliday.addAccommodation(currentAccommodation);
            currentAccommodation = null;
        }
    }

    public void removeAccommodation() {
        manager.removeAccommodationFromTrip(currentHoliday.getId(),accommodationId);

        for (Accommodation a : getCurrentHoliday().getAccommodation()) {
            if (a.getId().equals(accommodationId)) {
                getCurrentHoliday().getAccommodation().remove(a);
                break;
            }
        }

    }

    public List<Transportation> getFoundTransports() {
        return manager.findTransportsByExample(getTransportExample());
    }

    public String removeHoliday() {
        manager.removeHoliday(currentHolidayId);
        return null;
    }

}

BlueTravelWeb/web/view/client.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<body>
<ui:composition template="/template/blue_travel.xhtml">
    <ui:define name="pageTitle">#{local.customerDetail}</ui:define>
    <ui:define name="metadata">
        <f:metadata>
            <f:viewParam name="clientId" value="#{customerController.selectedCustomerId}" required="true"/>
        </f:metadata>
    </ui:define>
    <ui:define name="primaryContent">

        <h3>#{local.detailsFor} #{customerController.currentCustomer.name}</h3>
        <rich:panel>
            <f:facet name="header">#{local.trips}</f:facet>
            <!-- DOPLNIT: Obarvení vnitřního panelu -->
            <rich:dataGrid value="#{customerController.currentCustomer.contracts}" var="contract">
                <rich:panel rendered="#{contract ne null}"
                            style="background-color: #{customerController.backgroundColor[contract.confirmed]};">
                    <ucl:trip value="#{contract.holiday}"/>
                </rich:panel>
            </rich:dataGrid>
        </rich:panel>
    </ui:define>
</ui:composition>
</body>
</html>

BlueTravelWeb/web/view/client_list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:body>
    <ui:composition template="/template/blue_travel.xhtml">
        <ui:define name="pageTitle">#{local.clientList}</ui:define>
        <ui:define name="primaryContent">
            <h:form>
                <h:panelGrid columns="3">
                    <h:outputText value="#{local.surname}: "/>
                    <h:inputText value="#{customerController.searchSurname}"/>
                    <h:commandButton value="#{local.search}" action="#{customerController.searchCustomers}">
                        <a4j:ajax execute="@form" render="customers"/>
                    </h:commandButton>
                </h:panelGrid>

                <br/>
                <hr/>
                <br/>
                <br/>

                <rich:dataTable id="customers" var="customer"
                                value="#{customerController.customersFound}">
                    <rich:column>
                        <f:facet name="header">#{local.firstName}</f:facet>
                        #{customer.firstName}
                    </rich:column>
                    <rich:column>
                        <f:facet name="header">#{local.surname}</f:facet>
                        #{customer.surname}
                    </rich:column>
                    <rich:column>
                        <h:link value="#{local.select}" outcome="show_detail" includeViewParams="true">
                            <f:param name="clientId" value="#{customer.id}"/>
                        </h:link>
                    </rich:column>
                </rich:dataTable>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

BlueTravelWeb/web/view/trip.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">
<h:body>
    <ui:composition template="/template/blue_travel.xhtml">
        <ui:define name="pageTitle">#{local.tripDetail}</ui:define>
        <ui:define name="metadata">
            <f:metadata>
                <f:viewParam name="tripId" value="#{holidayManager.currentHolidayId}"/>
            </f:metadata>
        </ui:define>
        <ui:define name="primaryContent">
            <h:form>
                <rich:collapsiblePanel header="#{local.details}">
                    <h:panelGrid columns="3">
                        <h:outputText value="#{local.name}: "/>
                        <h:inputText id="holidayName" value="#{holidayManager.currentHoliday.name}"/>
                        <rich:message for="holidayName"/>

                        <h:outputText value="#{local.starts}: "/>
                        <rich:calendar id="holidayStarts" datePattern="dd.M.yyyy"
                                       value="#{holidayManager.currentHoliday.starts}"/>
                        <rich:message for="holidayStarts"/>

                        <h:outputText value="#{local.ends}: "/>
                        <rich:calendar id="holidayEnds" datePattern="dd.M.yyyy"
                                       value="#{holidayManager.currentHoliday.ends}"/>
                        <rich:message for="holidayEnds"/>

                        <h:outputText value="#{local.price}: "/>
                        <h:inputText id="holidayPrice" value="#{holidayManager.currentHoliday.price}"/>
                        <rich:message for="holidayPrice"/>
                    </h:panelGrid>
                    <h:commandButton value="#{local.save}" action="#{holidayManager.saveHoliday}">
                        <f:ajax execute="@form" render="@form"/>
                    </h:commandButton>
                </rich:collapsiblePanel>
            </h:form>
            <rich:panel>
                <f:facet name="header">#{local.transportation}</f:facet>
                <h3>#{local.existingTransportation}</h3>
                <h:form>
                    <rich:dataTable id="transportTable" var="transport"
                                    value="#{ucl:asList(holidayManager.currentHoliday.transportation)}">
                        <rich:column>
                            <f:facet name="header">#{local.type}</f:facet>
                            #{transport.type}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.dateLeaving}</f:facet>
                            <h:outputText value="#{transport.departure}">
                                <f:convertDateTime type="date"/>
                            </h:outputText>
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.timeLeaving}</f:facet>
                            <h:outputText value="#{transport.departure}">
                                <f:convertDateTime type="time"/>
                            </h:outputText>
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.fromLocation}</f:facet>
                            #{transport.from}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.toLocation}</f:facet>
                            #{transport.to}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.duration}</f:facet>
                            <h:outputText value="#{(transport.arrival.time - transport.departure.time)/3600000}">
                                <f:convertNumber maxFractionDigits="1"/>
                            </h:outputText>
                        </rich:column>
                        <rich:column>
                            <a4j:commandLink value="#{local.remove}" action="#{holidayManager.removeTransport}"
                                             render="@form">
                                <f:setPropertyActionListener target="#{holidayManager.transportId}"
                                                             value="#{transport.id}"/>
                            </a4j:commandLink>
                        </rich:column>
                    </rich:dataTable>
                </h:form>
                <h3>#{local.findAddTransportation}</h3>
                <h:form>
                    <h:panelGrid columns="2">
                        <h:outputText value="#{local.cityFrom}:"/>
                        <h:selectOneMenu value="#{holidayManager.transportExample.from}">
                            <f:selectItems value="#{holidayManager.allFromCities}"/>
                        </h:selectOneMenu>

                        <h:outputText value="#{local.cityTo}:"/>
                        <h:selectOneMenu value="#{holidayManager.transportExample.to}">
                            <f:selectItems value="#{holidayManager.allToCities}"/>
                        </h:selectOneMenu>

                        <h:outputText value="#{local.departureDate}:"/>
                        <rich:calendar datePattern="dd.M.yyyy" value="#{holidayManager.transportExample.departure}"/>
                    </h:panelGrid>
                    <h:commandLink value="#{local.findTransports}">
                        <a4j:ajax execute="@form" render="foundTransports"/>
                    </h:commandLink>
                </h:form>
                <h3>#{local.foundTransportation}</h3>
                <h:form>
                    <rich:dataTable id="foundTransports" var="transport" value="#{holidayManager.foundTransports}">
                        <rich:column>
                            <f:facet name="header">#{local.type}</f:facet>
                            #{transport.type}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.dateLeaving}</f:facet>
                            <h:outputText value="#{transport.departure}">
                                <f:convertDateTime type="date"/>
                            </h:outputText>
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.timeLeaving}</f:facet>
                            <h:outputText value="#{transport.departure}">
                                <f:convertDateTime type="time"/>
                            </h:outputText>
                        </rich:column>
                        <rich:column>
                            <a4j:commandLink value="#{local.addTransportation}" action="#{holidayManager.addTransport}"
                                             render="transportTable">
                                <f:setPropertyActionListener target="#{holidayManager.transportId}"
                                                             value="#{transport.id}"/>
                            </a4j:commandLink>
                        </rich:column>
                    </rich:dataTable>
                </h:form>
            </rich:panel>

            <rich:panel rendered="#{holidayManager.currentHoliday.id ne null}" id="accPanel">
                <f:facet name="header">#{local.accommodation}</f:facet>
                <h:form id="accForm">
                    <rich:dataTable id="accommodations" var="stay"
                                    value="#{ucl:asList(holidayManager.currentHoliday.accommodation)}">
                        <rich:column>
                            <f:facet name="header">#{local.location}</f:facet>
                            #{stay.location}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.hotel}</f:facet>
                            #{stay.hotelName}
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.dayFrom}</f:facet>
                            <h:outputText value="#{stay.dayFrom}">
                                <f:convertDateTime type="date"/>
                            </h:outputText>
                        </rich:column>
                        <rich:column>
                            <f:facet name="header">#{local.dayTo}</f:facet>
                            <h:outputText value="#{stay.dayTo}">
                                <f:convertDateTime type="date"/>
                            </h:outputText>
                        </rich:column>
                        <rich:column>
                            <a4j:commandLink value="#{local.removeAccommodation}"
                                             action="#{holidayManager.removeAccommodation}" render="accommodations">
                                <f:setPropertyActionListener target="#{holidayManager.accommodationId}"
                                                             value="#{stay.id}"/>
                            </a4j:commandLink>
                        </rich:column>
                    </rich:dataTable>
                </h:form>
                <br/>
                <h:form>
                    <h:panelGrid columns="3">
                        <h:outputText value="#{local.location}: "/>
                        <h:selectOneMenu id="accLocation" value="#{holidayManager.currentAccommodation.location}">
                            <f:selectItem itemValue="" selected="true"/>
                            <c:forEach items="#{holidayManager.allHotelCities}" var="hotelCity">
                                <f:selectItem itemValue="#{hotelCity}"/>
                            </c:forEach>
                            <a4j:ajax event="change" execute="@this" render="accommodationInfo"/>
                        </h:selectOneMenu>
                        <rich:message for="accLocation"/>
                    </h:panelGrid>
                </h:form>

                <h:form id="accommodationInfo">
                    <h:panelGrid columns="3">
                        <h:outputText value="#{local.hotel}: "/>
                        <h:selectOneMenu id="selectedHotel" value="#{holidayManager.currentAccommodation.hotelName}">
                            <c:forEach items="#{holidayManager.hotelsForSelectedCity}" var="hotel">
                                <f:selectItem itemValue="#{hotel}"/>
                            </c:forEach>
                        </h:selectOneMenu>
                        <rich:message for="selectedHotel"/>

                        <h:outputText value="#{local.from}: "/>
                        <rich:calendar id="accommodationFrom" datePattern="dd.M.yyyy"
                                       value="#{holidayManager.currentAccommodation.dayFrom}"/>
                        <rich:message for="accommodationFrom"/>

                        <h:outputText value="#{local.to}: "/>
                        <rich:calendar id="accommodationTo" datePattern="dd.M.yyyy"
                                       value="#{holidayManager.currentAccommodation.dayTo}"/>
                        <rich:message for="accommodationTo"/>

                    </h:panelGrid>
                    <rich:messages/><br/>
                    <a4j:commandButton value="#{local.save}" execute="@form" action="#{holidayManager.addAccommodation}"
                                       render="accPanel"/>
                    <a4j:commandLink value="#{local.save}" execute="@form" action="#{holidayManager.addAccommodation}"
                                     render="accPanel"/>

                    <!-- day to  -->
                </h:form>
            </rich:panel>
        </ui:define>
    </ui:composition>

</h:body>
</html>

BlueTravelWeb/web/view/trip_list.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich">
<body>
<ui:composition template="/template/blue_travel.xhtml">
    <ui:define name="pageTitle">#{local.tripList}</ui:define>
    <ui:define name="primaryContent">
        <h:form>
            <rich:dataTable var="trip" value="#{holidayManager.allHolidays}">
                <rich:column>
                    <f:facet name="header">#{local.name}</f:facet>
                    #{trip.name}
                </rich:column>
                <rich:column>
                    <f:facet name="header">#{local.starts}</f:facet>
                    #{trip.starts}
                </rich:column>
                <rich:column>
                    <f:facet name="header">#{local.ends}</f:facet>
                    #{trip.ends}
                </rich:column>
                <rich:column>
                    <f:facet name="header">#{local.price}</f:facet>
                    #{trip.price}
                </rich:column>
                <rich:column>
                    <h:commandLink value="#{local.tripRemove}" action="#{holidayManager.removeHoliday}">
                        <f:setPropertyActionListener target="#{holidayManager.currentHolidayId}" value="#{trip.id}"/>
                    </h:commandLink>
                </rich:column>
                <rich:column>
                    <h:link value="#{local.tripDetail}" outcome="show_detail" includeViewParams="true">
                        <f:param name="tripId" value="#{trip.id}"/>
                    </h:link>
                </rich:column>
            </rich:dataTable>
        </h:form>
    </ui:define>
</ui:composition>
</body>
</html>