BlueResortsWeb/src/cz/ucl/jsf/HotelController.java
package cz.ucl.jsf;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import cz.ucl.br.ejb.HotelManager;
import cz.ucl.br.model.Hotel;
import cz.ucl.br.model.Room;

@ManagedBean(name = "hotelController")
@ViewScoped
public class HotelController implements Serializable {
    @EJB
    private HotelManager manager;

    private Map<Long, Hotel> allHotels;
    private Long selectedHotelId;
    private Hotel selectedHotel;

    private Long selectedRoomId;
    private Room room;

    private void initHotels() {
        if (allHotels == null) {
            allHotels = new TreeMap<Long, Hotel>();
            for (Hotel h : manager.listHotels())
                allHotels.put(h.getId(), h);
        }
    }

    public List<Hotel> getHotelList() {
        initHotels();

        return new ArrayList<Hotel>(allHotels.values());
    }

    public void setSelectedHotelId(Long selectedHotelId) {
        if (selectedHotelId != null && !selectedHotelId.equals(this.selectedHotelId)) {
            this.selectedHotelId = selectedHotelId;
            initHotels();
            selectedHotel = manager.selectHotel(allHotels.get(selectedHotelId));
        } else if (selectedHotelId == null && this.selectedHotelId != null) {
            this.selectedHotelId = null;
            this.selectedHotel = null;
        }
    }

    public Long getSelectedHotelId() {
        return this.selectedHotelId;
    }

    public boolean isHotelSelected() {
        return (selectedHotel != null);
    }

    public Hotel getSelectedHotel() {
        return selectedHotel;
    }

    public String closeHotel() {
        manager.closeHotel();

        selectedHotel = null;
        selectedHotelId = null;

        return "hotel_closed";
    }

    public void setSelectedRoomId(Long selectedRoomId) {
        if (selectedRoomId != null
                && (!selectedRoomId.equals(this.selectedRoomId))) {
            for (Room r : selectedHotel.getRooms()) {
                if (r.getId().equals(selectedRoomId)) {
                    room = r;
                    break;
                }
            }
            this.selectedRoomId = selectedRoomId;
        } else if (selectedRoomId == null && this.selectedRoomId != null) {
            this.selectedRoomId = null;
            this.room = null;
        }
    }

    public Long getSelectedRoomId() {
        return this.selectedRoomId;
    }

    public boolean isRoomSelected() {
        return (selectedRoomId != null);
    }

    public Room getRoom() {
        if (room == null)
            room = new Room();
        return room;
    }

    public String addRoom() {
        manager.addRoom(room);
        selectedHotel.getRooms().add(room);
        room = null;
        return "room_added";
    }

    public String changeRoom() {
        manager.changeRoom(room);
        return "room_changed";
    }

    public String removeRoom() {
        manager.removeRoom(room);
        selectedHotel.getRooms().remove(room);
        return "room_removed";
    }

}

BlueResortsWeb/src/cz/ucl/jsf/ReservationController.java
package cz.ucl.jsf;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import cz.ucl.br.ejb.NoCancellationException;
import cz.ucl.br.ejb.NoRoomAvailableException;
import cz.ucl.br.ejb.ReservationManager;
import cz.ucl.br.model.Hotel;

@ManagedBean(name = "reservationController")
@ViewScoped
public class ReservationController implements Serializable {
    @EJB
    private ReservationManager manager;

    private String location;

    private String hotelName;
    private String customerName;
    private int bedCount = 2;
    private Date from;
    private Date to;

    private String reservationCode;

    private List<String> allLocations;
    private List<Hotel> localHotels;

    public String getHotelName() {
        return hotelName;
    }

    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public int getBedCount() {
        return bedCount;
    }

    public void setBedCount(int bedCount) {
        this.bedCount = bedCount;
    }

    public Date getFrom() {
        return from;
    }

    public void setFrom(Date from) {
        this.from = from;
    }

    public Date getTo() {
        return to;
    }

    public void setTo(Date to) {
        this.to = to;
    }

    public String getReservationCode() {
        return reservationCode;
    }

    public void setReservationCode(String reservationCode) {
        this.reservationCode = reservationCode;
    }

    public List<String> getAllLocations() {
        if (allLocations == null) {
            allLocations = manager.getAllLocations();
            setLocation(allLocations.get(0));
        }
        return allLocations;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        if ((location != null) && (!location.equals(this.location))) {
            localHotels = manager.findHotels(location);
        }
        this.location = location;
    }

    public List<Hotel> getLocalHotels() {
        return localHotels;
    }

    public String createReservation() {
        try {
            String newReservationCode = manager.createReservation(hotelName, customerName, bedCount, from, to);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Reservation created with code " + newReservationCode, "Reservation created"));
            return "reservation_created";
        } catch (NoRoomAvailableException e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "No rooms available: ", "No rooms available for your request - please try another date"));
            return null;
        }
    }

    public String cancelReservation() {
        try {
            manager.cancelReservation(reservationCode);
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Reservation cancelled", "Reservation with code " + reservationCode + " was cancelled"));
            return "reservation_cancelled";
        } catch (NoCancellationException e) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Cancellation not possible: ", e.getReason()));
            return null;
        }
    }

}

BlueResortsWeb/src/cz/ucl/jsf/TaxiController.java
package cz.ucl.jsf;

import java.io.Serializable;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import cz.ucl.br.ejb.TaxiRequestManager;
import cz.ucl.br.model.TaxiRequest;

@ManagedBean(name = "taxiController")
@ViewScoped
public class TaxiController implements Serializable {
    @EJB
    private TaxiRequestManager manager;

    private TaxiRequest request;

    public TaxiController() {
        super();

        request = new TaxiRequest();
    }

    public TaxiRequest getRequest() {
        return request;
    }

    public String sendRequest() {
        Long requestId = manager.requestTaxi(request);
        FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Taxi request sent (ID " + requestId + ")", "Taxi request sent (ID " + requestId + ")"));
        return "request_sent";
    }

}

BlueResortsWeb/web/WEB-INF/tags/hotel.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:body>
    <ui:component>
        <h:form>
            <rich:collapsiblePanel header="#{local.hotelDetails}">
                <h:panelGrid columns="2">
                    <h:outputText value="#{local.name}: " style="font-weight: bold;"/>
                    <h:outputText value="#{value.name}"/>

                    <h:outputText value="#{local.location}: " style="font-weight: bold;"/>
                    <h:outputText value="#{value.location}"/>

                    <h:outputText value="#{local.description}: " style="font-weight: bold;"/>
                    <h:outputText value="#{value.description}"/>
                </h:panelGrid>
            </rich:collapsiblePanel>
        </h:form>
    </ui:component>
</h:body>
</html>

BlueResortsWeb/web/index.xhtml
<?xml version="1.0" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">
<h:head/>
<h:body>
    <ui:composition template="/template/page.xhtml">
        <ui:define name="pageTitle">#{local.welcomeScreen}</ui:define>
        <ui:define name="primaryContent">
            <rich:messages/>
            #{local.welcomeMessage}
        </ui:define>
    </ui:composition>
</h:body>
</html>

BlueResortsWeb/web/template/page.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich">
<h:head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title><ui:insert name="pageTitle">SEM07</ui:insert></title>
</h:head>
<ui:insert name="metadata"/>
<h:body>
    <rich:panel>
        <h:form>
            <rich:toolbar>
                <rich:dropDownMenu>
                    <f:facet name="label">#{local.hotel}</f:facet>
                    <rich:menuItem submitMode="server" label="#{local.selectHotel}" action="mm_select_hotel"
                                   disabled="#{hotelController.hotelSelected}"/>
                    <rich:menuItem submitMode="server" label="#{local.closeHotel}"
                                   action="#{hotelController.closeHotel}" disabled="#{!hotelController.hotelSelected}"/>
                </rich:dropDownMenu>
                <rich:dropDownMenu disabled="#{!hotelController.hotelSelected}">
                    <f:facet name="label">#{local.rooms}</f:facet>
                    <rich:menuItem submitMode="server" label="#{local.addRoom}" action="mm_room_add"/>
                    <rich:menuItem submitMode="server" label="#{local.listRooms}" action="mm_room_list"/>
                </rich:dropDownMenu>
                <rich:dropDownMenu disabled="#{hotelController.hotelSelected}">
                    <f:facet name="label">#{local.taxi}</f:facet>
                    <rich:menuItem submitMode="server" label="#{local.sendRequest}" action="mm_taxi_request"/>
                </rich:dropDownMenu>
                <rich:dropDownMenu disabled="#{hotelController.hotelSelected}">
                    <f:facet name="label">#{local.reservations}</f:facet>
                    <rich:menuItem submitMode="server" label="#{local.createReservation}"
                                   action="mm_reservation_create"/>
                    <rich:menuItem submitMode="server" label="#{local.cancelReservation}"
                                   action="mm_reservation_cancel"/>
                </rich:dropDownMenu>
            </rich:toolbar>
        </h:form>

        <h2><ui:insert name="pageTitle">SEM07</ui:insert></h2>
        <ui:insert name="primaryContent">Primary content</ui:insert>

    </rich:panel>
</h:body>
</html>

BlueResortsWeb/web/view/cancel_reservation.xhtml
<?xml version="1.0" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:head/>
<h:body>
    <ui:composition template="/template/page.xhtml">
        <ui:define name="pageTitle">#{local.cancelReservation}</ui:define>
        <ui:define name="primaryContent">
            <h:form>
                <rich:messages showDetail="true"/>
                <h:panelGrid columns="2">
                    <h:outputText value="#{local.reservationCode}: "/>
                    <h:inputText value="#{reservationController.reservationCode}" size="20" required="true"/>
                </h:panelGrid>
                <br/>
                <h:commandButton value="#{local.cancelReservationButton}"
                                 action="#{reservationController.cancelReservation}"/>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

BlueResortsWeb/web/view/create_reservation.xhtml
<?xml version="1.0" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:head/>
<h:body>
    <ui:composition template="/template/page.xhtml">
        <ui:define name="pageTitle">#{local.createReservation}</ui:define>
        <ui:define name="primaryContent">

            <h:form id="reservationForm">
                <rich:messages tooltip="true"/>

                <h:panelGrid columns="3">
                    <h:outputText value="#{local.location}: "/>
                    <h:selectOneMenu value="#{reservationController.location}" required="true">
                        <a4j:ajax event="change" render="reservationForm" execute="@this"/>
                        <c:forEach items="#{reservationController.allLocations}" var="location">
                            <f:selectItem itemValue="#{location}" itemLabel="#{location}"/>
                        </c:forEach>
                    </h:selectOneMenu>
                    <h:outputText value=""/>

                    <h:outputText value="#{local.hotel}: "/>
                    <h:selectOneMenu value="#{reservationController.hotelName}" required="true">
                        <c:forEach items="#{reservationController.localHotels}" var="hotel">
                            <f:selectItem itemValue="#{hotel.name}" itemLabel="#{hotel.name}"/>
                        </c:forEach>
                    </h:selectOneMenu>
                    <h:outputText value=""/>

                    <h:outputText value="#{local.beds}: "/>
                    <rich:inputNumberSpinner id="bedCount" value="#{reservationController.bedCount}" minValue="1"
                                             maxValue="10" required="true"/>
                    <rich:message for="bedCount"/>

                    <h:outputText value="#{local.customerName}: "/>
                    <h:inputText id="customerName" value="#{reservationController.customerName}" required="true"/>
                    <rich:message for="customerName"/>

                    <h:outputText value="#{local.dayFrom}: "/>
                    <rich:calendar id="dayFrom" datePattern="d.M.yyyy" popup="false"
                                   value="#{reservationController.from}" required="true"/>
                    <rich:message for="dayFrom"/>

                    <h:outputText value="#{local.dayTo}: "/>
                    <rich:calendar id="dayTo" datePattern="d.M.yyyy" popup="false" value="#{reservationController.to}"
                                   required="true"/>
                    <rich:message for="dayTo"/>

                </h:panelGrid>
                <h:commandButton value="#{local.create}" action="#{reservationController.createReservation}"/>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

BlueResortsWeb/web/view/hotel_list.xhtml
<?xml version="1.0" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:head/>
<h:body>
    <ui:composition template="/template/page.xhtml">
        <ui:define name="pageTitle">#{local.hotelList}</ui:define>
        <ui:define name="primaryContent">
            <h:form>
                <rich:dataTable var="hotel" value="#{hotelController.hotelList}">
                    <rich:column>
                        <f:facet name="header">#{local.name}</f:facet>
                        #{hotel.name}
                    </rich:column>
                    <rich:column>
                        <f:facet name="header">#{local.location}</f:facet>
                        #{hotel.location}
                    </rich:column>
                    <rich:column>
                        <f:facet name="header">#{local.description}</f:facet>
                        #{hotel.description}
                    </rich:column>
                    <rich:column>
                        <h:link value="#{local.select}" outcome="hotel_selected" includeViewParams="true">
                            <f:param name="hotelId" value="#{hotel.id}"/>
                        </h:link>
                    </rich:column>
                </rich:dataTable>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>

BlueResortsWeb/web/view/manage_room.xhtml
<?xml version="1.0" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:head/>
<h:body>
    <ui:composition template="/template/page.xhtml">
        <ui:define name="pageTitle">
            <h:outputText value="#{local.addRoom}" rendered="#{!hotelController.roomSelected}"/>
            <h:outputText value="#{local.changeRoom}" rendered="#{hotelController.roomSelected}"/>
        </ui:define>

        <ui:define name="metadata">
            <f:metadata>
                <f:viewParam name="hotelId" value="#{hotelController.selectedHotelId}" required="true"/>
                <f:viewParam name="roomId" value="#{hotelController.selectedRoomId}" required="false"/>
            </f:metadata>
        </ui:define>

        <ui:define name="primaryContent">

            <ucl:hotel value="#{hotelController.selectedHotel}"/>

            <br/>
            <h3>#{local.roomData}</h3>

            <h:form>

                <h:panelGrid columns="3">
                    <h:outputText value="#{local.roomNumber}: "/>
                    <h:inputText id="roomNumber" value="#{hotelController.room.number}" size="6" required="true"/>
                    <rich:message for="roomNumber"/>

                    <h:outputText value="#{local.floor}: "/>
                    <rich:inputNumberSpinner id="floor" value="#{hotelController.room.floor}" minValue="0"
                                             maxValue="100" required="true"/>
                    <rich:message for="floor"/>

                    <h:outputText value="#{local.beds}: "/>
                    <rich:inputNumberSpinner id="bedCount" value="#{hotelController.room.beds}" minValue="1"
                                             maxValue="10" required="true"/>
                    <rich:message for="bedCount"/>

                    <h:outputText value="#{local.description}: "/>
                    <h:inputTextarea id="description" value="#{hotelController.room.description}" cols="50" rows="10"/>
                    <rich:message for="description"/>

                    <br/>

                </h:panelGrid>
                <h:commandButton value="#{local.addRoomButton}" action="#{hotelController.addRoom}"
                                 rendered="#{!hotelController.roomSelected}"/>
                <h:commandButton value="#{local.changeRoomButton}" action="#{hotelController.changeRoom}"
                                 rendered="#{hotelController.roomSelected}"/>
                <h:commandButton immediate="true" value="#{local.cancelButton}" action="cancel"/>

                <br/>
                <h:commandLink value="#{local.removeRoom}" action="#{hotelController.removeRoom}"
                               rendered="#{hotelController.roomSelected}"/>
            </h:form>

        </ui:define>
    </ui:composition>
</h:body>
</html>

BlueResortsWeb/web/view/room_list.xhtml
<?xml version="1.0" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:head/>
<h:body>
    <ui:composition template="/template/page.xhtml">
        <ui:define name="pageTitle">#{local.roomList}</ui:define>
        <ui:define name="metadata">
            <f:metadata>
                <f:viewParam name="hotelId" value="#{hotelController.selectedHotelId}" required="true"/>
            </f:metadata>
        </ui:define>
        <ui:define name="primaryContent">
            <ucl:hotel value="#{hotelController.selectedHotel}"/>

            <br/>
            <h3>#{local.rooms}</h3>

            <h:form>
                <rich:dataTable var="room" value="#{ucl:asList(hotelController.selectedHotel.rooms)}">
                    <rich:column>
                        <f:facet name="header">#{local.number}</f:facet>
                        #{room.number}
                    </rich:column>
                    <rich:column>
                        <f:facet name="header">#{local.beds}</f:facet>
                        #{room.beds}
                    </rich:column>
                    <rich:column>
                        <f:facet name="header">#{local.floor}</f:facet>
                        #{room.floor}
                    </rich:column>
                    <rich:column>
                        <f:facet name="header">#{local.description}</f:facet>
                        <h:outputText value="#{room.description}" escape="false"/>
                    </rich:column>
                    <rich:column>
                        <h:link value="#{local.changeRoom}" outcome="change_room" includeViewParams="true">
                            <f:param name="roomId" value="#{room.id}"/>
                            <f:param name="hotelId" value="#{hotelController.selectedHotelId}"/>
                        </h:link>
                    </rich:column>
                </rich:dataTable>
                <br/>
                <h:link value="#{local.addRoom}" outcome="add_room" includeViewParams="true">
                    <f:param name="hotelId" value="#{hotelController.selectedHotelId}"/>
                </h:link>
            </h:form>

        </ui:define>
    </ui:composition>
</h:body>
</html>

BlueResortsWeb/web/view/taxi_request.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:a4j="http://richfaces.org/a4j"
      xmlns:rich="http://richfaces.org/rich"
      xmlns:ucl="http://www.unicorcollege.cz/JEE/Library">
<h:head/>
<h:body>
    <ui:composition template="/template/page.xhtml">
        <ui:define name="pageTitle">#{local.sendTaxiRequest}</ui:define>
        <ui:define name="primaryContent">

            <h:form id="taxiRequestForm">
                <rich:messages tooltip="true"/>

                <h:panelGrid columns="3">
                    <h:outputText value="#{local.location}: "/>
                    <h:selectOneMenu value="#{taxiController.request.location}" required="true">
                        <c:forEach items="#{reservationController.allLocations}" var="location">
                            <f:selectItem itemValue="#{location}" itemLabel="#{location}"/>
                        </c:forEach>
                    </h:selectOneMenu>
                    <h:outputText value=""/>

                    <h:outputText value="#{local.placeFrom}: "/>
                    <h:inputText id="placeFrom" value="#{taxiController.request.from}" required="true"/>
                    <rich:message for="placeFrom"/>

                    <h:outputText value="#{local.placeTo}: "/>
                    <h:inputText id="placeTo" value="#{taxiController.request.to}" required="true"/>
                    <rich:message for="placeTo"/>

                    <h:outputText value="#{local.distance}: "/>
                    <rich:inputNumberSpinner id="distance" value="#{taxiController.request.distance}" minValue="1"
                                             maxValue="100" required="true"/>
                    <rich:message for="distance"/>

                    <h:outputText value="#{local.customerName}: "/>
                    <h:inputText id="customerName" value="#{taxiController.request.clientName}" required="true"/>
                    <rich:message for="customerName"/>

                    <h:outputText value="#{local.customerContact}: "/>
                    <h:inputText id="customerContact" value="#{taxiController.request.clientContact}" required="true"/>
                    <rich:message for="customerContact"/>

                </h:panelGrid>
                <br/>
                <h:commandButton value="#{local.send}" action="#{taxiController.sendRequest}"/>
            </h:form>
        </ui:define>
    </ui:composition>
</h:body>
</html>